spring.application.name=backend
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.omrjdzgnfnpggrilzxxe
spring.datasource.password=MEDTRACK@SIH2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
